# Generated by Django 6.0.2 on 2026-02-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.IntegerField(default=1, unique=True, verbose_name='Telegram ID'),
            preserve_default=False,
        ),
    ]
