# Generated by Django 5.2.11 on 2026-02-04 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(max_length=500, unique=True)),
                ('place', models.CharField(max_length=50, unique=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('is_pleasant', models.BooleanField(default=False)),
                ('periodicity', models.PositiveIntegerField(default=1)),
                ('reward', models.IntegerField(default=0)),
                ('time_to_complete', models.IntegerField(blank=True, default=0, null=True, verbose_name='Time To Complete')),
                ('is_public', models.BooleanField(default=True)),
                ('related_habits', models.ManyToManyField(related_name='related_habits', to='habits.habit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Habit',
                'verbose_name_plural': 'Habits',
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='RelatedHabits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_habits_links', to='habits.habit')),
                ('related_habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_to_links', to='habits.habit')),
            ],
        ),
    ]
